version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: oj-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: oj
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build: ./backend
    container_name: oj-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/oj
      - JWT_SECRET=your_jwt_secret_change_in_production
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: oj-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongodb_data: 